{% set python_min = '3.12' %}
{% set name = "llama-utils" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Serapieum-of-alex/llama-utils/archive/{{ version }}.tar.gz
  sha256: ba303344ce8e90d944667ae421cc1f6be0a4844e879e34cffc4e6708b61ae158

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python {{ python_min }}
    - poetry
    - pip
  run:
    - python >={{ python_min }}
    - llama-index >=0.12.12
    - pandas >=2.2.3


test:
  requires:
    - python {{ python_min }}
  imports:
    - llama_utils

about:
  home: https://github.com/Serapieum-of-alex/llama-utils
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: llama-index utility package
  description: |
    llama-index utility package.
  dev_url: https://github.com/Serapieum-of-alex/llama-utils
  doc_url: https://serapieum-of-alex.github.io/llama-utils
  doc_source_url: https://github.com/Serapieum-of-alex/llama-utils/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
